### ISSUE TITLE
Jinx-2

### ISSUE THREAD

**Issue by Dimitv125** [Taiizor/Store#11]
### App Version

24.11.26.0

### Wallpaper Location

Anime/Jinx-2

### Wallpaper Version

1.0.0.0

### Wallpaper App Version

24.11.27.0

### Report Reason

Other

### Report Description

I cant use wallpaper even if i had last update

**Comment by Taiizor** [comment]
@Dimitv125 Yes, while your current Sucrose version (24.11.26.0) is up-to-date, the wallpaper in question requires version 24.11.27.0, which is a developer version.

Updates are delivered to users through two separate channels. Therefore, when checking for updates, you might mistakenly think you are using the latest version.

You can follow the instructions in [this YouTube video](https://www.youtube.com/watch?v=9N5RqjqgPSM) to change your update channel. Please note, however, that by doing so, you will be trying less stable versions.
