### ISSUE TITLE
Wonderful-1

### ISSUE THREAD

**Issue by Ghost-Shadow-Dead** [Taiizor/Store#7]
### Wallpaper Location

Music/Wonderful-1

### Report Reason

Other

### Report Description

unable to use

**Comment by Taiizor** [comment]
Every theme added to the store is released with the latest Sucrose version compiled/published on that day. This version may not have been released yet or may have been released for the Development Channel.

![Sucrose-Wallpaper-Engine](https://github.com/Taiizor/Store/assets/41683699/9af90bea-6980-407d-86dc-29b73ea5a103)

The theme you mentioned is released for version 24.3.11.0 and later. Therefore, if you are using a lower Sucrose version, you naturally cannot use this theme.

![Sucrose-Wallpaper-Engine](https://github.com/Taiizor/Store/assets/41683699/25857bca-22f7-48ca-affa-9e305912732d)

The latest released Sucrose version is currently 24.3.7.0. Therefore, you need to wait for a newer version of Sucrose.

**Comment by Taiizor** [comment]
Sucrose version 24.3.30.0 has been released, and as of today, after updating Sucrose, you can use all themes in the store.
